title: Sem01
description: "DB Collector automation"
remote_theme: just-the-docs/just-the-docs

url: https://JJotace.github.io/

aux_links:
  JIRA Project: to do

footer_content: "Juan Cardoso - Sem01 - Technische Berufsschule Zürich - Cloud Native Engineering - 2025"